### ISSUE TITLE
os.Exit not supported in browser, causes unexpected behavior.

### ISSUE THREAD

**Issue by theclapp** [gopherjs/gopherjs#371] opened 2016-01-02 19:01 UTC
This works in native Go (see [here](http://play.golang.org/p/WMU_sThtu2)) but crashes in GopherJS ([GopherJS playground](http://www.gopherjs.org/playground/#/FEFclW4BXo)), and uses 100% cpu:

```go
const jsonStream = `
{"Name": "Ed", "Text": "Knock knock."}
{"Name": "Sam", "Text": "Who's there?"}
{"Name": "Ed", "Text": "Go fmt."}
{"Name": "Sam", "Text": "Go fmt who?"}
{"Name": "Ed", "Text": "Go fmt yourself!"}
`
type Message struct {
	Name, Text string
}
dec := json.NewDecoder(strings.NewReader(jsonStream))

var m Message
for {
	// decode an array value (Message)
	err := dec.Decode(&m)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%v: %v\n", m.Name, m.Text)
}
```

Expected output:
Ed: Knock knock.
Sam: Who's there?
Ed: Go fmt.
Sam: Go fmt who?
Ed: Go fmt yourself!
2009/11/10 23:00:00 EOF

Actual output:
no output, 100% cpu usage for that browser tab

**Comment by dominikh** [comment] 2016-01-02 19:31
Simpler way of demonstrating the issue:

```
package main

import (
	"log"
)

func main() {
	log.Println("start")
	log.Fatal("fatal")
	log.Println("end")
}
```

(http://www.gopherjs.org/play/#/V3JYv4vxWU)

log.Fatal calls os.Exit, which invokes a syscall. GopherJS doesn't support syscalls in the browser and just continues. This effectively breaks log.Fatal.

I'll defer to Richard for an actual decision, but personally I'm wondering if exit should be supported in some way, though it's far from trivial.

**Comment by shurcooL** [comment] 2016-01-02 21:50
This is related to #229.

The lifetime of a native Go app ends when main exits, but a lifetime of a web app script (compiled from Go via GopherJS) ends when the page is closed.

This issue is about `os.Exit` not being supported.

A way I can see it be supported is if there's some browser API to stop running all scripts. After all, you'd want to make all goroutines exit too.

**Comment by theclapp** [comment] 2016-01-02 22:59
This is not the error I thought it was.  I was trying to create a minimal test case of a problem I'm having in a larger app involving a gopherjs.websocket, which seems to be having problems detecting EOF.

The log.Fatal is incidental to the test case (from my point of view) and is not used in my larger app.  I replaced it with fmt.Printf in the playground and everything was fine.

For this error, it's kind of bad that it crashes the browser (or at least that tab), but I, for one, wouldn't think you should jump through a bunch of hoops to kill everything when main exits.  As @dominikh says in #229, "Goroutines aren't explicitly killed, it's a side effect of, well, the program not running anymore."  From my point of view, the browser page is the analog of the program, and so goroutines should only stop when you close the page (or navigate away, or whatever).

So I don't use os.Exit() or log.Fatal(), so as far as I'm concerned, you can close this bug (well, except for the 100% cpu usage), and if I figure out what's actually going wrong in my app, I'll open another one.

**Comment by shurcooL** [comment] 2016-01-02 23:46
I see. We can use this issue to track `os.Exit` then.

> This is not the error I thought it was. I was trying to create a minimal test case of a problem I'm having in a larger app involving a gopherjs.websocket, which seems to be having problems detecting EOF.

Could it be https://github.com/gopherjs/websocket/issues/7 that you're running into? If it's a bug specific to `websocket` package, please use its issue tracker.

**Comment by theclapp** [comment] 2016-01-03 00:13
> Could it be gopherjs/websocket#7 that you're running into?

I don't think it's that error specifically, but could be something related.  I'm doing a read (indirectly via `json.Decode()`) in one goroutine, and another closes the websocket, and as near as I can tell the read (the `Decode()`) never gets the eof.

> If it's a bug specific to websocket package, please use its issue tracker.

Will do.

And just by the way, thanks for everyone's eyeballs on this, and apologies for the false alarm.

**Comment by theclapp** [comment] 2016-01-03 03:21
Just to f/up on the non-bug in websocket and not leave anybody hanging on that score: it only _looked_ like the read never gets the EOF.  I found that Chrome was taking 2 seconds (almost exactly) to deliver the "onclose" event, and my test exited before that.  I changed my server to close the connection when it gets the EOF on its end, and then the onclose event was delivered within a few (~4) milliseconds.  (Sending a "close" websocket control message didn't seem to make it any better.)

**Comment by neelance** [comment] 2016-01-07 10:29
What's the intended behavior of `os.Exit` in the web browser?

One option would be to Immediately terminate all goroutines and on callbacks from JS print a warning and do not execute code. But is it worth to support this?

**Comment by theclapp** [comment] 2016-01-07 13:18
I, for one, don't think it's worth it to support that.

os.Exit should probably either panic, or (in a browser) js.Global.Call("close").  Or maybe $("body").empty().  :)

I don't know what the Node equivalent would be.

**Comment by flimzy** [comment] 2016-01-07 13:34
Closing the window, or clearing the page seems wrong to me.  This would be a bit like doing a clear screen when a program crashes on the console.

js.Global.Call("stop") seems a lot better to me.

**Comment by theclapp** [comment] 2016-01-07 15:28
> This would be a bit like doing a clear screen when a program crashes on the console.

That's a reasonable point.  I was looking at it from the point of view of a GUI program where all the windows close.

> Will throwing an error (I suppose that's what you mean by panic, right?) not accomplish what one might expect

Well, I meant a panic() on the Go side.  And panicing only ends the current goroutine, so that wouldn't be the same as os.Exit() on a server.  I'm not sure whether throwing a JS error would be the same, either; I think it might just end the current callback or event.

I think it's reasonable to "look behind the curtain" a little, admit that GopherJS might be running in a browser, and allow installation of a handler that os.Exit calls, so the developer can decide what to do in that case.  Sort of like catching a signal.

How much effort would it be to halt all goroutines and close all channels?  I'd guess that trying to have all callbacks print a warning would be pretty difficult; how do you know something's a callback?

Heck, maybe it should just keep doing what it's doing: use 100% of the cpu and don't yield.  Though that would suck for an end-user, so maybe not.

**Comment by neelance** [comment] 2016-01-15 00:21
Officially the `os` package is not supported in a browser. For convenience, we may add some fallback implementation, just like we have for writing to stdout/stderr for making `fmt.Println` work. I'd say that the minimal solution would be enough for most cases: Call `runtime.Goexit()`, nothing more. It would avoid the infinite loop in the example above.

**Comment by neelance** [comment] 2016-01-17 23:51
@theclapp Please take a look at the `lifecycle` branch. I implemented the `runtime.Goexit` approach mentioned above. Is this a good solution for you?

**Comment by theclapp** [comment] 2016-01-20 14:53
The code looks good and seems like it'd be fine.  I haven't had a chance to try it yet, sorry, but didn't want to leave you hanging too long.

**Comment by theclapp** [comment] 2016-01-21 12:03
Tried it this morning.  It does seem to work.  Thanks!

**Closed** 2016-01-23 20:06 UTC
