### ISSUE TITLE
import cycle causing `gopherjs build` infinite loop

### ISSUE THREAD

**Issue by electricface** [gopherjs/gopherjs#917] opened 2019-05-15 06:07 UTC
```
+ go build frontend
import cycle not allowed
package frontend
    imports frontend/component
    imports frontend/store
    imports frontend/component
```

**Comment by flimzy** [comment] 2019-05-16 08:39
Possible duplicate of https://github.com/gopherjs/gopherjs/issues/414

**Comment by dmitshur** [comment] 2019-05-20 13:04
I think this is a duplicate. I’ll close it, but please let us know if this issue is not the same as that one.

**Closed by dmitshur** 2019-05-20 13:04 UTC
