### ISSUE TITLE
Profiling and optimizing more heavyweight workload.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#142] opened 2014-12-28 21:39 UTC
Hi @neelance,

In the past I've used GopherJS successfully for some medium-weight workloads, and performance has always been "good enough not be noticeable or cause any concerns."

Recently I [had a chance](https://twitter.com/shurcooL/status/549105400184700929) to use it for a more significant amount of work, and I'm seeing a quite large discrepancy between native and JS performance.

Native Go:

```
Read 1960081 of 1960081 bytes.
Done loading track in: 95.778819ms
```

Go compiled to JavaScript in browser:

```
Read 1960081 of 1960081 bytes.
Done loading track in: 27.944s
```

The browser execution is around 300x slower. I see the browser tab reaching over 1 GB of RAM while loading the track.

The workload can be seen [here](https://github.com/shurcooL/play/blob/e53557dd9c070ce0ec5251108249e5fa85333ae0/95/script.go#L357-L464). It is loading a 2 MB binary file and then parsing it, doing a lot slice allocations and `binary.Read`. The 2 MB binary file (fetched via XHR) is wrapped in a `bytes.NewReader` (and another reader to count length read). Clearly, the Go code was written in the most easy to write and read way, without special considerations for performance.

I tried to take a CPU profile in browser, and this is what I got:

![image](https://cloud.githubusercontent.com/assets/1924134/5565027/536e0f0c-8e95-11e4-8a26-dfee01bd407f.png)

Basically, I wanted to ask for some thoughts:

1. Does the performance seem reasonable, or it possible there's some single issue/bad practice contributing to a lot of performance degradation?
    - I notice the `newTrack` func is called `$blocking_newTrack`, I wonder if that makes sense.
2. Is the 500 MB - 1.1 GB of RAM usage in the browser table also expected? The native Go binary uses ~50 MB of RAM.
3. Any other hints/tips on other ways I could profile it, other things to try to gain performance. For this task, I would be happy to get to less than 1~5 second track loading time (but that might not be realistic).
4. General thoughts and comments if you have any. :)

If you want to reproduce it, it should be straightforward. I've outlined steps in https://github.com/shurcooL/play/commit/e53557dd9c070ce0ec5251108249e5fa85333ae0#commitcomment-9101168. (I use `gopherjs_serve_html` for quicker iterations, but you can just use `gopherjs build script.go` and change `index.html` to use `script.js` instead.)

Of course, I think the current results are pretty mind blowing, and being able to have it work at all is fantastic! Note that once the track finishes loading, I am able to get 30-60 FPS actually rendering it, so it's quite usable. At the same time, this could be a good benchmark to try various things and see how performance is affected. Hopefully, 30 seconds is just the beginning.

**Comment by shurcooL** [comment] 2015-01-05 02:37
Wow!

I saw that recent comments mention this issue, so I was curious to compare performance between the older version dc3319ff3966516efeaf976d6e116cd5d6140770 and the latest f5c1d85c4c:

```
before:
Done loading track in: 14.381s
Done loading track in: 14.299s

after:
Done loading track in: 7.954s
Done loading track in: 7.892s
Done loading track in: 7.724s
```

Also, I see the browser tab now only uses 180-220 MB of memory the whole time, unlike the 500-1200 MB before!

That's an incredible improvement @neelance! (For reference, it was 28~ seconds when I opened this issue.)

**Comment by neelance** [comment] 2015-01-05 03:05
Now I'm done with optimizing. The last change was a bit dirty, but it seems to work fine. ;-) Please try it again.

**Comment by shurcooL** [comment] 2015-01-05 03:22
Are you kidding me? I can't believe this works! So fast!

With d30b2ca:

```
Done loading track in: 2.74s
Done loading track in: 2.77s
Done loading track in: 2.492s
Done loading track in: 2.846s
Done loading track in: 2.833s
```

I still can't believe my eyes!

**Comment by shurcooL** [comment] 2015-01-05 07:26
Just benchmarked the previous 2 versions on iPad too (edited posts above for multiple run numbers), to get a more complete picture, here's a summary:

```
computer: 14s -> 7s -> 3s
iPad: 35s -> 20s -> 13s
```

Amazing job! I'm not seeing any issues so far, just increased performance.

**Comment by neelance** [comment] 2015-01-05 11:47
I'm glad that your like it. :-)

**Comment by shurcooL** [comment] 2015-03-01 04:02
Now that #89 has been merged into master, I wanted to take a look at performance hit for this benchmark.

Before, it was 2.5~ seconds.

This is after:

![image](https://cloud.githubusercontent.com/assets/1924134/6429424/7ead4c62-bf84-11e4-8828-89c694965fa7.png)

Is this normal/expected because of the assume-blocking logic? Is there room for optimization left?

(Note, this "benchmark" is relatively slow Go code that I didn't optimize; it can definitely be faster by avoiding the use of slow `binary` package.)

**Comment by neelance** [comment] 2015-03-07 00:00
Closing this again until #193 is implemented.

**Comment by neelance** [comment] 2015-03-09 02:23
Please try again now. :-)

**Comment by shurcooL** [comment] 2015-03-10 02:42
Strange, unlike #192, it seems to have gotten worse than before.

Version | `...play/95`, Done loading track in:
|----------|------------------:|
Last Assume Blocking, with `//gopherjs:blocking` requirement (30fcbd836780ca9b8c9694f5491cf3b2a502f1a8) | 2.916s
Current Version (e89b87d9817883db7dfca7d65f408d6d07f8eb3e) | 18.07s

Let me know if you want me to test some in-between versions.

I've noticed that this benchmark's performance got **substantially** worse a few commits ago, like 55~ seconds, and the latest improvements to the assume blocking work as described in #193 and reflected by current version, improved performance back to ~18 seconds.

Note that 18 seconds is worse than the 13 seconds that I reported earlier, which was after assume blocking was applied.

Any thoughts? Why did performance of `vdom` bench in #192 improve but this one got worse?

**Comment by neelance** [comment] 2015-03-10 03:29
I just did some profiling. Seems like it is now spending a lot of time in the `binary` and `reflect` packages, since it is all considered blocking. The `//gopherjs:non-blocking` comment would be quite useful here. I'll investigate some more.

Could you check again those 13.249s, please? That seems really strange to me.

**Comment by shurcooL** [comment] 2015-03-10 03:39
Sure, I will find out which commit that was and try it again now.

**Comment by shurcooL** [comment] 2015-03-10 03:43
I made that comment 9 days ago, so I made a guess that it was commit d4a817594ad3b76ceb29a96d8ab888f501c5f8fb (also 9 days ago), and it seems to be about right. With that commit, I get:

> Done loading track in: 11.191s

**Comment by neelance** [comment] 2015-03-10 04:06
Yeah, I just reverted b9df71d9e7baa1afc21df952f75c925a217d829a on master to go back to assuming non-blocking and then it is still slow, even though there is no blocking overhead in the code any more. Thanks for bringing that to my attention, I'll find out what's going on.

**Comment by neelance** [comment] 2015-03-10 12:35
This will take a few steps, I'll tell you when it's ready.

**Comment by neelance** [comment] 2015-03-10 15:21
Okay, I've fixed the performance regressions. Learned even more about what JS engines don't like. ;-) The remaining overhead is due to assuming blocking, but it is quite okay in my opinion.

**Comment by shurcooL** [comment] 2015-03-10 17:00
Thank you Richard! The latest version is performing much much better:

Version | `...play/95`
-----------|-------
e89b87d9817883db7dfca7d65f408d6d07f8eb3e | Done loading track in: 16.355s
18f1d721d4708124375603307aa0e28fd5938d69 | Done loading track in: 4.049s

**Closed** 2015-03-10 18:20 UTC
