### ISSUE TITLE
BUG: 1 << 62 (untyped int constant 4611686018427387904) overflows uint

### ISSUE THREAD

**Issue by rudolph9** [gopherjs/gopherjs#951] opened 2019-12-13 17:10 UTC
The following runs in Golang 1.12: 

```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
	var i uint
	if i > 1<<62 {
		fmt.Errorf("bit index too large")
	}
}
```

but results in a compile error with GopherJS 1.12-2
```
1 << 62 (untyped int constant 4611686018427387904) overflows uint
```

**Comment by hajimehoshi** [comment] 2019-12-13 17:32
GopherJS assumes 32bit architecture (i.e., `unsafe.Sizeof(int) == 4`). It is the same as the playground: https://play.golang.org/p/mjtsrkXLasZ

**Comment by rudolph9** [comment] 2019-12-13 18:06
Here is a related ticket https://github.com/cuelang/cue/issues/227

**Comment by hajimehoshi** [comment] 2019-12-13 18:07
I'll close this since this is an expected behavior.

**Closed by hajimehoshi** 2019-12-13 18:07 UTC

**Comment by rudolph9** [comment] 2019-12-13 18:09
So `1` in golang is architecture dependent?

**Comment by hajimehoshi** [comment] 2019-12-13 18:37
`1` is untyped and `1 << 62` is also untyped. There is no maximum value of untyped integers, but when they are converted to other types (`uint` in this case), they must be in the range of the concrete type.

https://golang.org/ref/spec#Constants

> A constant may be given a type explicitly by a constant declaration or conversion, or implicitly when used in a variable declaration or an assignment or as an operand in an expression. It is an error if the constant value cannot be represented as a value of the respective type.

**Comment by mpvl** [comment] 2019-12-16 10:37
It is fine to always take `uint64` for CUE's purpose.
