### ISSUE TITLE
gopherjs serve: "cannot find package" error doesn't say where the package was imported

### ISSUE THREAD

**Issue by alltom** [gopherjs/gopherjs#564] opened 2016-12-29 09:57 UTC
If I import a non-existent package and run `gopherjs serve`, the console output doesn't tell me where the erroneous import statement is:

```
$ gopherjs serve --http :8081
serving at http://localhost:8081 and on port 8081 of any available addresses
cannot find package "mario/render" in any of:
	/usr/local/Cellar/go/1.7.4/libexec/src/mario/render (from $GOROOT)
	/Users/tom/go-mario/src/mario/render (from $GOPATH)
```

**Comment by flimzy** [comment] 2017-01-02 10:34
Possible duplicate of #290 ?

**Comment by alltom** [comment] 2017-01-03 05:53
Seems like it.

**Closed** 2017-01-03 05:54 UTC
