### ISSUE TITLE
Undeclared names on Mac M1

### ISSUE THREAD

**Issue by aragonet** [gopherjs/gopherjs#1027] opened 2021-05-17 10:39 UTC
When I try to compile using the latest version of gopherjs (1.16.1+go1.16.3) this is the output errors:

gopherjs build
../../../../../src/syscall/syscall_darwin.go:11:25: undeclared name: libc_stat64_trampoline
../../../../../src/syscall/syscall_darwin.go:13:25: undeclared name: libc_fstat64_trampoline
../../../../../src/syscall/syscall_darwin.go:15:25: undeclared name: libc_lstat64_trampoline

I've compiled the same code on linux and compiles fine. Maybe its something related to Mac M1 arm64.

Thanks in advance

**Comment by nevkontakte** [comment] 2021-05-17 10:40
Could you please share your `go env` printout?

**Comment by aragonet** [comment] 2021-05-17 15:12
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xxxxx/Library/Caches/go-build"
GOENV="/Users/xxxxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxxxxx/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/xxxxxx/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxxxx/logic/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sy/ht4qsj_n66v25g6d7v91thtc0000gn/T/go-build1093755415=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by nevkontakte** [comment] 2021-05-18 21:45
Actually, https://github.com/gopherjs/gopherjs/pull/1024 might have fixed this already, but we forgot to tag a new release with it. Could you try GopherJS from master and see if you still have a problem? If not, I'll tag a new release tomorrow.

**Comment by aragonet** [comment] 2021-05-19 07:14
I've installed from master, and the error stills appearing.

**Comment by nevkontakte** [comment] 2021-05-19 19:20
Can you provide a minimal reproduction example and the exact commands you've used?

I've tried the following and it worked just fine:

```
package main

import (
        "fmt"
        "syscall"
)

func main() {
        buf := [4]byte{}
        fmt.Println(syscall.Read(syscall.Stdin, buf[:]))
        fmt.Println(buf)
}
```

`$ GOOS=darwin GOARCH=arm64 gopherjs build .`

Unfortunately, I don't have access to an M1 mac, so this is the closes I can get to reproducing an error.

**Comment by nevkontakte** [comment] 2021-05-23 13:04
@aragonet could you please provide a minimal reproduction example? Otherwise I'll assume this is a duplicate of https://github.com/gopherjs/gopherjs/issues/1023.

**Comment by aragonet** [comment] 2021-05-24 08:39
Sorry for answering a bit late. Just tried to build the code you provided and the same three lines of output appear.

```
gopherjs build .
../../../../../src/syscall/syscall_darwin.go:11:25: undeclared name: libc_stat64_trampoline
../../../../../src/syscall/syscall_darwin.go:13:25: undeclared name: libc_fstat64_trampoline
../../../../../src/syscall/syscall_darwin.go:15:25: undeclared name: libc_lstat64_trampoline
```

If there is any way I can help you find the problem I'll be pleased.

**Comment by nevkontakte** [comment] 2021-05-24 09:48
Ok, thanks, confirming this is still an issue. It is strange that it builds just fine for me despite setting GOOS/GOARCH to match yours. Perhaps, there's a deeper bug lurking about here... I'll investigate more sometime this week.

**Closed** 2021-05-30 22:11 UTC
