### ISSUE TITLE
Bug in fallthrough of $internalize pointer types.

### ISSUE THREAD

**Issue by davewalker-wk** [gopherjs/gopherjs#1301] opened 2024-04-26 18:21 UTC
The following highlights a problem when $internalize ing a pointer type.  It _only_ will internalize if the pointer is a struct; otherwise it will fallthrough into internalizing as a slice.

Suspect code: https://github.com/gopherjs/gopherjs/blob/master/compiler/prelude/jsmapping.js#L329-L334

```go
//go:build js

package test

import (
	"fmt"
	"github.com/gopherjs/gopherjs/js"
	"testing"
)

type Bar struct {
	*js.Object
	V *string `js:"V"`
}

func makeJsObject() *js.Object {
	if js.Global != nil {
		return js.Global.Get("Object").New()
	}

	return nil
}

func TestExposeBug(t *testing.T) {
	b := Bar{Object: makeJsObject()}
	b.V = nil
	elem := b.V
	fmt.Println(elem)
}
```

**Comment by nevkontakte** [comment] 2024-04-30 20:21
Upon closer inspection this is duplicate of #1231.

**Comment by nevkontakte** [comment] 2024-04-30 20:23
Duplicate of #1231.

**Closed** 2024-04-30 20:23 UTC
Labels: bug
