### ISSUE TITLE
gopherjs transpiles non-compiling code

### ISSUE THREAD

**Issue by myitcv** [gopherjs/gopherjs#458] opened 2016-05-10 18:18 UTC
Given:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, playground")
	x := A{}
	println("Hello, JS console", x)
}

type A struct{}
```

then:

```bash
$ go build
# github.com/myitcv/gopherjs_test
./main.go:8: illegal types for operand: print
        A
```

and yet:

```bash
$ gopherjs build main.go
$ echo $?
0
```

Apologies if I'm missing something obvious here?

```bash
$ go version
go version go1.6.2 linux/amd64
$ (cd $GOPATH/src/github.com/gopherjs/gopherjs; git log -1 --oneline)
ce68d34 compiler/natives/syscall: Don't import bytes package.
```

**Comment by myitcv** [comment] 2016-05-10 18:21
Amended the original comment to include version details

**Comment by shurcooL** [comment] 2016-05-11 05:35
Is there a spec for the signature of `print` and `println` pre-declared identifiers? I know their _implementation_ is not well defined as it's meant to be a basic debugging tool. From [Go spec](https://golang.org/ref/spec#Bootstrapping):

> Current implementations provide several built-in functions useful during bootstrapping. These functions are documented for completeness but are not guaranteed to stay in the language. They do not return a result.
>
>     Function   Behavior
>
>     print      prints all arguments; formatting of arguments is implementation-specific
>     println    like print but prints spaces between arguments and a newline at the end

And from https://golang.org/pkg/builtin/#print:

>     func print(args ...Type)
>
> The print built-in function formats its arguments in an implementation-specific way and writes the result to standard error. Print is useful for bootstrapping and debugging; it is not guaranteed to stay in the language.

>     func println(args ...Type)
>
> The println built-in function formats its arguments in an implementation-specific way and writes the result to standard error. Spaces are always added between arguments and a newline is appended. Println is useful for bootstrapping and debugging; it is not guaranteed to stay in the language.

So the funcs exact formatting behavior is not specified, but the signature seems to be clear.

However, I'm surprised the following Go code doesn't compile with `gc`:

```Go
package main

func main() {
	print(A{})
}

type A struct{}
```

```
prog.go:4: illegal types for operand: print
	A
```

Because [`Type`](https://golang.org/pkg/builtin/#Type) is defined as:

> Type is here for the purposes of documentation only. It is a stand-in for any Go type, but represents the same type for any given function invocation.

I'm not sure we can fix this issue in GopherJS until we figure out what the spec for those 2 predeclared funcs is, if any.

**Comment by myitcv** [comment] 2016-05-11 07:49
@shurcooL 

> Is there a spec for the signature of `print` and `println` pre-declared identifiers?

I don't know for sure. 

The main thing I wanted to flag is that it a non-compiling piece of Go code is permitted by `gopherjs`. Whilst there may be further derivative questions to answer with respect to specs etc in this case, it was the fact `gopherjs` didn't error on this that surprised me (because other non-compiling code might similarly be "accepted" with undefined results)

**Comment by shurcooL** [comment] 2016-05-11 08:34
> because other non-compiling code might similarly be "accepted" with undefined results

I see your point, but I don't think this is indicative of other potential places where GopherJS would compile something that `gc` wouldn't. `print` is meant to be a simple, implementation-specific tool for debugging, and frankly, I think it's more likely a minor bug in `gc` that it can't `print(A{})`.

GopherJS implements `print` and `println` very simply, by joining the arguments and calling `console.log`, see [here](https://github.com/gopherjs/gopherjs/blob/ce68d341900a377d121b925cf3454b5af31fa79d/compiler/expressions.go#L914-L915).

If there's a spec saying it shouldn't do that, we can fix it, but otherwise it's probably fine to leave as is.

If you find any such issues elsewhere, they should absolutely be fixed. But it's probably okay to give `print` some slack as long as it prints the passed values.

To make progress here, I think we need to raise an issue on Go or post on the mailing list and find out whether `println(A{})` failing to compile is intended or an unexpected bug. Are you willing to do that @myitcv?

**Comment by myitcv** [comment] 2016-05-11 08:50
> If you find any such issues elsewhere, they should absolutely be fixed. But it's probably okay to give `print` some slack as long as it prints the passed values.

Just wanted to flag the 'incident' so very happy with whatever conclusion you reach.

> To make progress here, I think we need to raise an issue on Go or post on the mailing list and find out whether `println(A{})` failing to compile is intended or an unexpected bug. Are you willing to do that @myitcv?

Yes, will do so later today.

Thanks for the quick response in any case.

**Comment by neelance** [comment] 2016-05-11 09:31
It's not a bug, it's a feature! ;-)

The semantics of `print` and `println` are not specified, but left up to the implementation. GopherJS translates them to `console.log` and thus prints the internal representation of the Go value. The output will be very different to what you get with `gc` and it is able to easily print whatever value you pass. `gc` on the other hand restricts the types you can pass to those which can be printed without much formatting logic. If you need to print complex types, then you'll have to use `fmt.Println` in `gc`.

I'll close this issue, because there is nothing to change on GopherJS here. :-)

**Closed by neelance** 2016-05-11 09:31 UTC

**Comment by myitcv** [comment] 2016-05-11 09:36
> It's not a bug, it's a feature! ;-)

We all ❤️   that phrase!

So this really is an edge case; it's legitimately the case that this code can compile in `gopherjs` but not `gc` and vice-versa?

In which case, there's no bug to raise on the Go side either then, agreed?

**Comment by neelance** [comment] 2016-05-11 09:41
Yes, I think so. `println` should never stay in the code for a long time, it is just intended for quick debugging use. Any code checked into version control should always use `fmt.Println` instead.

**Comment by myitcv** [comment] 2016-05-11 09:52
Thanks both.
