### ISSUE TITLE
fail to run gopherjs with Go1.6

### ISSUE THREAD

**Issue by siongui** [gopherjs/gopherjs#403] opened 2016-02-18 05:04 UTC
I got the following error message with Go1.6. The same code is ok to compile with Go1.5.3
````
gopherjs build gopherjs/*.go -o website/pali.js
stat ~/dev/go/src/runtime/zgoos_linux.go: no such file or directory
````

**Comment by flimzy** [comment] 2016-02-18 07:28
This looks like a duplicate of #355

**Comment by shurcooL** [comment] 2016-02-18 08:12
It is a duplicate of #355.

**Closed by shurcooL** 2016-02-18 08:12 UTC
Labels: duplicate
