### ISSUE TITLE
Gopherjs get fails to get dependencies

### ISSUE THREAD

**Issue by EtienneBruines** [gopherjs/gopherjs#455] opened 2016-05-09 16:47 UTC
I'm running at `travis`. The error message being:

```
cannot find package "honnef.co/go/js/dom" in any of:
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/honnef.co/go/js/dom (from $GOROOT)
	/home/travis/gopath/src/honnef.co/go/js/dom (from $GOPATH)
```

The command I'm running is:

```bash
    gopherjs get "engo.io/engo/demos/animation" || exit 1
```

I guess it has problems identifying the dependencies? Explicitly calling `gopherjs get honnef.co/go/js/dom` beforehand, does fix the problem - so I guess it has trouble detecting dependencies **recursively**? (the demo we're `gopherjs get`ing, depends on `engo.io/engo`, which in turn depends on those `honnef.co` packages. )

----
Originally I thought the `gopherjs build` afterwards was throwing that error, but apparently `gopherjs get` is.

**Comment by shurcooL** [comment] 2016-05-10 04:34
I'm having trouble go getting that Go package with normal `go get`. Is it a valid Go package?

```bash
$ go get engo.io/engo/demos/animation
package engo.io/engo/demos/animation: unrecognized import path "engo.io/engo/demos/animation" (parse https://engo.io/engo/demos/animation?go-get=1: no go-import meta tags)
```

https://godoc.org/engo.io/engo/demos/animation isn't showing it either. Can you confirm it's supposed to be working?

**Comment by shurcooL** [comment] 2016-05-24 08:32
I'll close this because I believe the issue is not in GopherJS, but with that import path.

`engo.io/engo/demos/animation` is not a valid Go package according to the vanity remote import resolution rules described at https://golang.org/cmd/go/#hdr-Remote_import_paths. More specifically, the page at https://engo.io/engo/demos/animation?go-get=1 is missing go-import meta tags. See the full error message in the comment above.

That means even `go get engo.io/engo/demos/animation` fails to work.

You should fix that first, and if GopherJS still fails to get it, then please reopen this issue.

**Closed by shurcooL** 2016-05-24 08:32 UTC
