### ISSUE TITLE
RangeError when using EventSource with vendored dependencies

### ISSUE THREAD

**Issue by jraedisch** [gopherjs/gopherjs#537] opened 2016-10-17 11:56 UTC
```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
	"honnef.co/go/js/util"
)

func main() {
	println("initializing")
	es := js.Global.Get("EventSource").New("/events")
	et := util.EventTarget{Object: es}
	et.AddEventListener("message", false, listener)
}

func listener(obj *js.Object) {
	println(obj)
}
```

Will fail in `$internalize case $kindStruct` when GopherJS and js/util are vendored:

```
source.js:2051 Uncaught RangeError: Maximum call stack size exceeded
searchJsObject	@	source.js:2051
searchJsObject	@	source.js:2063
searchJsObject	@	source.js:2060
searchJsObject	@	source.js:2063
...
```

Without vendoring, everything works fine.

You can create a simple EventStream like this (in case you don't have one lying around):

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"
)

func main() {
	http.HandleFunc("/events", EventsHandler)
	log.Fatal(http.ListenAndServeTLS(":8081", "selfsigned.crt", "selfsigned.key", nil))
}

// EventsHandler returns a stream of timestamp messages.
func EventsHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	notify := w.(http.CloseNotifier).CloseNotify()
	conn := true
	go func() {
		<-notify
		conn = false
	}()

	for conn {
		fmt.Fprintf(w, "data: %s\n\n", time.Now())
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		} else {
			log.Println("no flush")
		}
		time.Sleep(2 * time.Second)
	}
	log.Println("conn closed")
}
```

**Comment by myitcv** [comment] 2016-10-17 11:58
Possible dupe of https://github.com/gopherjs/gopherjs/issues/415 @shurcooL?

**Comment by jraedisch** [comment] 2016-10-17 11:59
I forgot to mention that other GopherJS code works fine, so I do not think that it is an exact dup.

**Comment by shurcooL** [comment] 2016-10-17 18:56
Yes, I think this is a duplicate of #415, since:

> Without vendoring, everything works fine.

Vendoring GopherJS is currently not supported and may manifest in various errors. #415 tracks the issue of supporting vendoring.

**Comment by shurcooL** [comment] 2016-10-17 19:02
@jraedisch, if that makes sense to you, let's close this issue for now. Once #415 is resolved, this should be resolved as well. If not, we can re-open it and investigate.

**Closed by shurcooL** 2016-10-17 19:02 UTC
Labels: duplicate

**Comment by jraedisch** [comment] 2016-10-17 20:14
@shurcooL the issue isn't so much that vendoring is not supported, but that it may manifest in so many different ways, that other people might not find #415. Maybe a more descriptive error message or an info in the README.md would be nice?

**Comment by shurcooL** [comment] 2016-10-17 20:25
> that other people might not find #415. Maybe a more descriptive error message or an info in the README.md would be helpful?

Yes, fully agreed, we should resolve it partially by at least documenting that limitation in the README. A single sentence would be fine.
